create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  category text not null,
  price numeric not null,
  description text,
  image_url text,
  created_at timestamptz default now()
);

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  customer_name text not null,
  phone text not null,
  email text,
  address text,
  items jsonb not null,
  total numeric not null default 0,
  payment_method text default 'whatsapp',
  payment_reference text,
  payment_status text default 'pending',
  status text default 'Pending',
  created_at timestamptz default now()
);

alter table public.products enable row level security;
alter table public.orders enable row level security;

create policy "public can read products"
on public.products for select
to anon, authenticated
using (true);

insert into public.products (name, category, price, description)
select * from (values
  ('Monogram Tote Bag','Bags',45000,'Spacious everyday luxury leather tote.'),
  ('Executive Chronograph Watch','Watches',85000,'Precision stainless steel timepiece.'),
  ('Classic Silk Shirt','Men',30000,'Tailored fit breathable silk shirt.'),
  ('Velvet Evening Clutch','Women',25000,'Statement accessory for special nights.'),
  ('Minimalist Chain Necklace','Accessories',15000,'Gold-plated timeless staple piece.'),
  ('Unisex Oversized Hoodie','Unisex',35000,'Heavyweight plush fleece comfort.')
) as v(name,category,price,description)
where not exists (select 1 from public.products);
